a=float(input("a sonni kiriting: "))
b=float(input("b sonni kiriting: "))
c=float(input("c sonni kiriting: "))
katta=max(a, b, c)
kichik=min(a, b, c)
print(f'eng kattasi={katta} eng kichigi={kichik}')